### ISSUE TITLE
hdiutil error: image not recognized

### ISSUE THREAD

**Issue by whazzmaster** [boxen/puppet-btsync#2]
It looks like the source dmg no longer resolves. Hitting [the currently-configured endpoint](http://btsync.s3-website-us-east-1.amazonaws.com/BTSync.dmg) returns:

```
400 Bad Request

Code: IncorrectEndpoint
Message: The specified bucket exists in another region. Please direct requests to the specified endpoint.
Endpoint: btsync.s3-website-eu-west-1.amazonaws.com
RequestId: 49DA4D3B1A8A71F7
HostId: HUipU75BQDZJW1PoLD+pEJ+0cZTty+Gxk53t+BfAqzloY2FXYDivdK1yRgQOrEOZ
```

Hitting [the endpoint](http://btsync.s3-website-eu-west-1.amazonaws.com/BTSync.dmg) suggested by that error message then returns:

```
404 Not Found

Code: NoSuchWebsiteConfiguration
Message: The specified bucket does not have a website configuration
BucketName: btsync
RequestId: 107885C4BDC6945F
HostId: D/ljrVqQ6Go/O5ZOfwCFFMdv+bj2hTm3K95m+m6nBtdBncEI68Ty9isBM4tXF4t5DCXe0ajXep8=
```

I'd submit a PR but I'm not sure where the correct resource resides (or if the resource is hosted _anywhere_ anymore.

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17
